/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElText: typeof import('element-plus/es')['ElText']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpFolderOpened: typeof import('~icons/ep/folder-opened')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    IEpStarFilled: typeof import('~icons/ep/star-filled')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
