/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    CursorPreview: typeof import('./src/components/CursorPreview.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmojiPicker: typeof import('./src/components/emojiPicker/emojiPicker.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDownload: typeof import('~icons/ep/download')['default']
    IEpFolderOpened: typeof import('~icons/ep/folder-opened')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpPlatform: typeof import('~icons/ep/platform')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    IEpStarFilled: typeof import('~icons/ep/star-filled')['default']
    IMsDeleteOutlineRounded: typeof import('~icons/material-symbols/delete-outline-rounded')['default']
    IMsDesktopMac: typeof import('~icons/material-symbols/desktop-mac')['default']
    IMsDownloadRounded: typeof import('~icons/material-symbols/download-rounded')['default']
    IMsKidStar: typeof import('~icons/material-symbols/kid-star')['default']
    IMsKidStarOutline: typeof import('~icons/material-symbols/kid-star-outline')['default']
    IMsTipsAndUpdatesOutlineRounded: typeof import('~icons/material-symbols/tips-and-updates-outline-rounded')['default']
    ISolarCursorLinear: typeof import('~icons/solar/cursor-linear')['default']
    List: typeof import('./src/components/List.vue')['default']
    MyTooltip: typeof import('./src/components/MyTooltip.vue')['default']
    Picker: typeof import('./src/components/emojiPicker/picker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
